### ISSUE TITLE
请问如何对接umi-ocr

### ISSUE THREAD

**Issue by a15355447898a** [2234839/OceanPress_siyuan_plugin#16]
我在服务器上面使用docker部署了umi-ocr

![Image](https://github.com/user-attachments/assets/e9dcbb41-0abe-4339-91ce-9b5d5e074714)

```yaml
services:
  umi-ocr:
    image: a15355447898a/umi-ocr:latest
    container_name: umi-ocr
    environment:
      HEADLESS: "true"
    ports:
      - 40010:1224
    restart: always
    networks:
      - valkyrie
networks:
  valkyrie:
    external: true
```

然后我在插件设置api

![Image](https://github.com/user-attachments/assets/17b30592-9c73-4514-93ed-3fa8a40ade6c)

但是尝试ocr的时候失败了

![Image](https://github.com/user-attachments/assets/27ffd64a-4c12-44fd-957c-9ac30ab89716)
